image: node:18

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

build_nuxt:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .output
