stages:
  - test
  - install
  - build
  - preview
  - review
  - deploy

variables:
  NODE_ENV: production
  # Forzamos la URL de clonación con el token de CI y el puerto correcto (8181 según tu configuración)
  GIT_CLONE_URL: "http://gitlab-ci-token:${CI_JOB_TOKEN}@51.44.94.84:8181/root/nuxt-app.git"

cache:
  paths:
    - node_modules/

# 1. Job de test
test:
  stage: test
  tags:
    - docker
  image: node:18-alpine
  script:
    - npm ci
    - npm test || echo "No tests configured, skipping"

# 2. Job de instalación de dependencias
install_dependencies:
  stage: install
  tags:
    - docker
  image: node:18-alpine
  script:
    - npm ci

# 3. Job de build
build_nuxt:
  stage: build
  tags:
    - docker
  image: node:18-alpine
  script:
    - npm run build
  artifacts:
    paths:
      - .output

# 4. Job de preview manual (útil para pruebas en local)
preview:
  stage: preview
  tags:
    - docker
  image: node:18-alpine
  when: manual
  allow_failure: true
  script:
    - npm run preview -- --port 3000 &
    - sleep 10
    - echo "✅ Preview started successfully — exiting job"
  timeout: 5m

# -------------------------------
# 5. Review Apps para Merge Requests
# -------------------------------
review_app:
  stage: review
  tags:
    - docker
  image: node:18-alpine
  script:
    - echo "Deploying Review App for branch $CI_COMMIT_REF_NAME"
    # (Opcional: puedes omitir el build si ya se ejecutó en build_nuxt)
    - npm run build
    # Crear directorio en el host de review apps
    - ssh $DEPLOY_USER@$REVIEW_HOST "mkdir -p ~/review-apps/$CI_COMMIT_REF_NAME"
    # Copiar la aplicación
    - scp -r .output/server/. $DEPLOY_USER@$REVIEW_HOST:~/review-apps/$CI_COMMIT_REF_NAME
    # Iniciar la app usando PM2 (ajusta el comando según necesites)
    - ssh $DEPLOY_USER@$REVIEW_HOST "pm2 restart review-$CI_COMMIT_REF_NAME || pm2 start ~/review-apps/$CI_COMMIT_REF_NAME/index.mjs --name review-$CI_COMMIT_REF_NAME"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_SLUG.example.com
    on_stop: stop_review_app
  only:
    - merge_requests

# Job para detener la Review App (se activa manualmente cuando se cierra el MR)
stop_review_app:
  stage: review
  tags:
    - docker
  image: node:18-alpine
  when: manual
  script:
    - echo "Stopping Review App for branch $CI_COMMIT_REF_NAME"
    - ssh $DEPLOY_USER@$REVIEW_HOST "pm2 delete review-$CI_COMMIT_REF_NAME || echo 'Review app already stopped'"
    - ssh $DEPLOY_USER@$REVIEW_HOST "rm -rf ~/review-apps/$CI_COMMIT_REF_NAME"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests

# -------------------------------
# 6. Despliegue en producción
# -------------------------------
deploy:
  stage: deploy
  tags:
    - docker
  image: node:18-alpine
  only:
    - main
  before_script:
    - apk update && apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p ~/nuxt-app"
    - scp -r .output/server/. $DEPLOY_USER@$DEPLOY_HOST:~/nuxt-app
    - ssh $DEPLOY_USER@$DEPLOY_HOST "pm2 restart nuxt-app || pm2 start ~/nuxt-app/index.mjs --name nuxt-app"
  environment:
    name: production
    url: http://$DEPLOY_HOST:8080
