stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Compilando la app..."
    - npm install
    - npm run build

deploy-job:
  stage: deploy
  script:
    - echo "Desplegando..."
    - npm run start # o el comando que uses en producción
