variables:
  GIT_STRATEGY: none   

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  tags:
    - docker
  script:
    - git clone http://51.44.94.84/root/nuxt-app.git .   
    - npm install

build_nuxt:
  stage: build
  tags:
    - docker
  script:
    - npm run build
  artifacts:
    paths:
      - .output
