stages:
  - test
  - install
  - build
  - preview
  - review
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

# Job de test
test:
  stage: test
  tags:
    - docker
  image: node:18-alpine
  script:
    - npm ci
    - npm test || echo "No tests configured, skipping"

# Job de instalación de dependencias
install_dependencies:
  stage: install
  tags:
    - docker
  image: node:18-alpine
  script:
    - npm ci

# Job de build
build_nuxt:
  stage: build
  tags:
    - docker
  image: node:18-alpine
  script:
    - npm run build
  artifacts:
    paths:
      - .output

# Job de preview manual
preview:
  stage: preview
  tags:
    - docker
  image: node:18-alpine
  when: manual
  allow_failure: true
  script:
    - npm run preview -- --port 3000 &
    - sleep 10
    - echo "✅ Preview started successfully — exiting job"
  timeout: 5m

# -------------------------------
# Review Apps for Merge Requests
# -------------------------------
review_app:
  stage: review
  tags:
    - docker
  image: node:18-alpine
  script:
    - echo "Deploying Review App for branch $CI_COMMIT_REF_NAME"
    # Construir la aplicación (puedes omitir este build si ya se realizó en build_nuxt)
    - npm run build
    # Desplegar la aplicación en el host de review
    - ssh $DEPLOY_USER@$REVIEW_HOST "mkdir -p ~/review-apps/$CI_COMMIT_REF_NAME"
    - scp -r .output/server/. $DEPLOY_USER@$REVIEW_HOST:~/review-apps/$CI_COMMIT_REF_NAME
    # Iniciar la aplicación usando PM2 (ajusta el comando según tu forma de iniciar la app)
    - ssh $DEPLOY_USER@$REVIEW_HOST "pm2 restart review-$CI_COMMIT_REF_NAME || pm2 start ~/review-apps/$CI_COMMIT_REF_NAME/index.mjs --name review-$CI_COMMIT_REF_NAME"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_SLUG.example.com
    on_stop: stop_review_app
  only:
    - merge_requests

# Job para detener la Review App (se activa cuando se cierra el MR)
stop_review_app:
  stage: review
  tags:
    - docker
  image: node:18-alpine
  script:
    - echo "Stopping Review App for branch $CI_COMMIT_REF_NAME"
    - ssh $DEPLOY_USER@$REVIEW_HOST "pm2 delete review-$CI_COMMIT_REF_NAME || echo 'Review app already stopped'"
    - ssh $DEPLOY_USER@$REVIEW_HOST "rm -rf ~/review-apps/$CI_COMMIT_REF_NAME"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - merge_requests

# -------------------------------
# deploying
# -------------------------------
deploy:
  stage: deploy
  tags:
    - docker
  image: node:18-alpine
  only:
    - main
  before_script:
    - apk update && apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p ~/nuxt-app"
    - scp -r .output/server/. $DEPLOY_USER@$DEPLOY_HOST:~/nuxt-app
    - ssh $DEPLOY_USER@$DEPLOY_HOST "pm2 restart nuxt-app || pm2 start ~/nuxt-app/index.mjs --name nuxt-app"
  environment:
    name: production
    url: http://$DEPLOY_HOST:8080
