stages:
  - test
  - install
  - build
  - preview
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

test:
  stage: test
  tags:
    - docker
  image: node:18-alpine
  script:
    - npm ci
    - npm test || echo "No tests configured, skipping"

install_dependencies:
  stage: install
  tags:
    - docker
  script:
    - npm ci

build_nuxt:
  stage: build
  tags:
    - docker
  script:
    - npm run build
  artifacts:
    paths:
      - .output

preview:
  stage: preview
  tags:
    - docker
  when: manual
  allow_failure: true
  script:
    - npm run preview -- --port 3000 &
    - sleep 10
    - echo "✅ Preview started successfully — exiting job"
  timeout: 5m

deploy:
  stage: deploy
  tags:
    - docker
  only:
    - main
  before_script:
    - apk update && apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p ~/nuxt-app"
    - scp -r .output/server/. $DEPLOY_USER@$DEPLOY_HOST:~/nuxt-app
    - ssh $DEPLOY_USER@$DEPLOY_HOST "pm2 restart nuxt-app || pm2 start ~/nuxt-app/index.mjs --name nuxt-app"
  environment:
    name: production
    url: http://$DEPLOY_HOST:8080

