image: node:18

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm ci

build_nuxt:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .output

deploy_to_server:
  stage: deploy
  script:
    - echo "Aquí iría tu script de despliegue, como rsync o scp"
    # Ejemplo:
    # - rsync -avz .output/ user@your-server:/var/www/nuxt
  only:
    - main
