stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  tags:
    - docker
  script:
    - npm ci

build_nuxt:
  stage: build
  tags:
    - docker
  script:
    - npm run build
  artifacts:
    paths:
      - .output
