// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/4/2025, 12:49:25
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Samuel/Documents/Empresa/my-nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/plugins/**/*.{js,ts,mjs}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/composables/**/*.{js,ts,mjs}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/utils/**/*.{js,ts,mjs}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/dashboard.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/ecommerce/config.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/ecommerce/logs.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/ecommerce/Order/[id].vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/ecommerce/orders_table.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/ecommerce/products/products_table.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/fio/config.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/fio/fio_table.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/fio/logs.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/fio/transaction/[id].vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/index.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/pages/login.vue","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Samuel/Documents/Empresa/my-nuxt-app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;